pipeline {
    agent any

    stages {
        stage('Setup') {
            steps{
                // Get Git Code manually
				//git(url: "${REPOSITORY}", credentialsId: 'xpc', branch: "${branch}")
				script {
                    // declare variables that are used in next steps
                    env.DOCKER_TAG = "registry.heroku.com/${APP_NAME}/web"
				}
			    //Clone Repo
				checkout scm
            }
        }

        stage('Maven build & test') {
            steps{
                // Run Maven
                sh "mvn clean package"
            }

            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                }
            }
        }

        stage('Docker build') {
            steps{
                sh "docker build -t ${env.DOCKER_TAG} ."
            }
        }

        stage('Push to registry') {
            steps{
                withCredentials([string(credentialsId: 'heroku-key', variable: 'HEROKU_API_KEY')]) {
                    sh "heroku container:login"
                    sh "docker push ${DOCKER_TAG}"
                }
            }
        }

        stage('Deploy') {
            steps{
                input message: 'Do you want to deploy the application?', ok: 'Yes'
                withCredentials([string(credentialsId: 'heroku-key', variable: 'HEROKU_API_KEY')]) {
                    sh "heroku container:release web -a ${APP_NAME}"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
